config/routes.rb
WdiProject3::Application.routes.draw do
  devise_for :users

  resources :rooms, only: :index do
  	collection { get :events }
  end

  get '/rooms/:id', to: "rooms#initialize_room", as: "room"
  get '/rooms/test_room', to: "rooms#test_room"
  get '/home/splash', to: "home#splash", as: 'splash'
  get '/home/masonry_test', to: "home#masonry_test"
  get '/home/room', to: "home#room"
  get '/home/index', to: "home#index", as:"all_rooms"

  post '/home/create', to: "home#create"
  post '/rooms/add_song', to: "rooms#add_song"
  post '/rooms/change_song', to: "rooms#change_song"
  post '/rooms/get_time', to: "rooms#get_time"
  post '/rooms/remove_user', to: "rooms#remove_user"
  post '/rooms/like_or_dislike', to: "rooms#like_or_dislike"
  post '/rooms/add_message', to: 'rooms#add_message'

  root 'home#splash'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_filter :authenticate_user!, :except => [:splash]

	def index
		@rooms = Room.all
		@room = Room.new
	end

	def splash
	end

	def create
		@room = Room.create(room_params)

		redirect_to room_path(@room)
	end

	def room_params
		params.require(:room).permit(:name)
	end

	def masonry_test
		@songs = Room.find(3).songs
	end

	def room
		@playlist = @room.songs.order('id')
	end



end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="all-rooms">
	<div id="all-rooms-mask">
		<div id='mask' class='close_modal'></div>
		<div id="options">
			<div id="create-room-link" class="modal">Create Room!</div>
			<div id="or"> OR </div>
			<div id="find-room">Find an Existing Room!</div>
		</div>
		<div id="create-room" class="modal-window">
			<%= form_for @room, url: "/home/create" do |f| %>
				<div id="name-field">
					<%= f.label 'Room Name:' %>
					<%= f.text_field :name %>
				</div>
				<div>
					<%= f.submit %>
				</div>
			<% end %>
		</div>
		<% if @rooms.length > 0 %>
			<ul id="room-list" class="roomlist">
				<% @rooms.each do |room| %>
					<li>
						<%= link_to room.name, room_path(room) %>
					</li>
				<% end %>
			</ul>
		<% else %>
			<ul id="room-list-empty" class="roomlist"> 
				<li>No rooms exist yet. Create one!</li> 
			</ul>
		<% end %>
	</div>
</div>

app/views/home/room.html.erb
<div id="main-container">

	<div id="main-page">
		aaaa
		<div id="logo-search">
			<i class="fa fa-search"></i>
		</div>

		<div id="logo-chat">
			<i class="fa fa-comment-o"></i>
		</div>

		<div id="chatroom">
			<div id="messages"></div>
			<div id="mess-wrap">
				<div id="message-input-wrap">
					<input id="message-input" type="text" placeholder="Enter message here..." />
				</div>
				<div id="send-button">
					<i id="send" class="fa fa-chevron-right"></i>
				</div>
			</div>
		</div>
	</div>

	<div id="search-bar">
		<div id="search-wrapper">
			<div id="search">
				<input type="text" name="search_box" id="search-text" size="27" placeholder="  Search">
			</div>
			<div id="search-button">
				<i id="search-chevron" class="fa fa-chevron-right"></i>
			</div>	
		</div>

		<div id="search-results">	

		</div>

	</div>

</div>

app/views/home/splash.html.erb
<div id = "splash-wrapper">
	<div id="splash-title"></div>
	<div id='mask' class='close_modal'></div> 
	<header>
		<ul id="splash-logo">
			<li><span id="logo-first-word">boom</span> <span id="logo-slash">//</span> <span id="logo-second-word">room</span></li>
		</ul>
		<ul id="splash-nav">
			<% if current_user %>
				<li><a id="next" href="/home/index"><i class="fa fa-arrow-right"></i></a></li>
				<li id="sign-out-link"><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
			<% else %>
				<li class="links modal" id="sign-in-link">Sign In</li> 
				<li class="links modal" id="sign-up-link">Sign Up</li>
			<% end %>
		</ul>		
	</header>		
	<div id="quote-first-line"><span class="quote">"</span>Without music,</div>
	<div id="quote-second-line">life would be a mistake.<span class="quote">"</span></div>
	<div id="quote-author">- Friedrich Nietzsche</div>

	<div id="sign-in" class="modal-window splash-modal">
		<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
			<div>
			  <%= f.email_field :email, :placeholder => 'E-mail', :autofocus => true %>
			</div>
			<div>
			  <%= f.password_field :password, :placeholder => 'Password' %>
			</div>
				<% if devise_mapping.rememberable? -%>
				  <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
				<% end %>
		  <div>
		  	<%= f.submit "Sign in" %>
		  </div>
		<% end %>
	</div>

	<div id="sign-up" class="modal-window splash-modal">
		<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
			<%= devise_error_messages! %>
			<div>
			  <%= f.email_field :email, :placeholder => 'E-mail', :autofocus => true %>
			</div>
			<div>
			  <%= f.text_field :username, :placeholder => 'Username' %>
			</div>
		  <div>
			  <%= f.password_field :password, :placeholder => 'Password' %>
			</div>
		  <div>
			  <%= f.password_field :password_confirmation, :placeholder => 'Password Confirmation' %>
			</div>
		  <div>
		  	<%= f.submit "Sign up" %>
			</div>
		<% end %>
	</div>
</div>